name: Release Terraform Module

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to use, has to be strict semver, like: 0.0.1'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@v4.2.2

    - uses: softprops/action-gh-release@v2.3.2
      with:
        tag_name: ${{ inputs.release_version }}
        name: Release ${{ inputs.release_version }}
        generate_release_notes: true
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
